---
- hosts: all
  user: vagrant #set root for use without vagrant
  become: true
  gather_facts: True

  roles:
  - common
  - webserver
  - mysql
  - icinga2
  - icingaweb2
  - icingaweb2_director
  - graphite

  post_tasks:
    - name: show setup token
      command: icingacli setup token show
      register: token

    - name: print token
      debug: var=token.stdout
