---
- name: Sets the root password
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Copy the my.cnf
  template:
    dest: /root/.my.cnf
    src: my.cnf.j2
    owner: root
    group: root
    mode: '0600'

- name: delete anonymous accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove the MySQL test database
  mysql_db:
    name: test
    state: absent
