---
- name: config ido_mysql.conf
  template:
    src: ido-mysql.conf
    dest: /etc/icinga2/features-available/ido-mysql.conf

# form ansible version 2.3 use icinga2_feature
- name: Enable ido-mysql and command feature
  command: icinga2 feature enable ido-mysql command
  notify:
    - restart icinga2

- name: add group icinga and icingacmd to apache
  user:
    name: apache
    groups: icinga,icingacmd,icingaweb2
    append: yes
  notify:
    - restart httpd

- name: Create setup token
  command: icingacli setup token create
