---
- name: Ensure some packages are installed
  yum:
    pkg: "{{ item }}"
    state: latest
#    enablerepo: "{{ required_repos }}"
  with_items: "{{ packages }}"
  when: packages is defined
  tags:
    - install
