---
- name: Ensure all services running
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ services }}"
  when: services is defined
  tags:
    - services
    
- name: start cockit.socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: True
